### ISSUE TITLE
Support for categoricals in Similarity Map (Dimensionality Reduction)

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#11]
Spotlight seems to improperly handle categorical variables in dimensionality reduction. When reducing only one categorical column, the distances appear to be sorted in alphabetical "order", so most likely, the distance metric (euclidean) does not take into account the categorical type of the variable. Note that it is in some cases also desirable to place a mix of categorical and numerical values. A strategy to also make the SimMap work on a Mix of variables would thus be desirable.

:warning: To reproduce run:
```
import pandas as pd
import numpy as np
from renumics import spotlight

df = pd.DataFrame(np.random.rand(10,3), columns=["feature_a", "feature_b", "feature_c"])
df["feature_cat"] = pd.Series(["b", "b", "b", "a", "a", "d", "d", "d", "c", "c"], dtype="category")
spotlight.show(df)
```
Now place feature_cat on the Similarity Map.

:1234: Spotlight Version is 1.0.0pre9

**Comment by markus-stoll** [comment]
thanks for the input. yes the simap could be improved here.... :
![image](https://user-images.githubusercontent.com/6725742/226597310-480ee0dd-5261-499f-9c4e-6bd961b53929.png)
We are working on it.
