### ISSUE TITLE
Allow wait=inf

### ISSUE THREAD

**Issue by chris-aeviator** [Renumics/spotlight#134]
When using spotlight I'd like to be able to share a spotlight instance via a link. However, since wait=True, the most permissive mode in that regard, will kill the instance when the "last browser" is closed, I cannot reliably do this.

I propose to introduce wait=inf to be able to deploy a long running spotlight instance.

**Comment by neindochoh** [comment]
Hey! Thanks for your suggestion. An additional option to keep the Spotlight instance running forever sounds rather useful to me.
How about `wait="forever"` to be more explicit?

For the time being, you can do something like this:
```python
import threading

spotlight.show(df, wait=False)
threading.Event().wait()
```

**Comment by chris-aeviator** [comment]
@neindochoh ja! Thanks for the workaround.

For sure setting wait to 'forever' will work too.
I saw the added benefit in not relying on a string


>>> wait = float('inf')
>>> wait > 1
True
>>> wait == 1
False
>>> wait < 1
False

>>> wait = False
>>> wait < 1
True 
...
