### ISSUE TITLE
Histogram displays misleading message when too many distinct values in a column

### ISSUE THREAD

**Issue by ssuwelack** [Renumics/spotlight#15]
If I have a string column with many different values (e.g. labels for problems with many classes) and I use the stacked histogram I get the following messages:

If I select the column as the "COLUMN" in the histogram, I get the message "No column selected" instead of "too many different values"

Example: BirdClef2023 dataset, column ('primary_label')

**Comment by steffenslavetinsky** [comment]
I am dividing this issue into two separate ones as they describe two distinct bugs.
