### ISSUE TITLE
Value of Text Widget in Inspector cannot be copied

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#170]
**Is your feature request related to a problem? Please describe.**
There is no way to mark and copy text from the Text widget in the inspector. Often this makes sense, e.g. for copying paths, prompts, or similar.

**Describe the solution you'd like**
I would love to be able to mark text and copy it out of the text widget.

**Comment by steffenslavetinsky** [comment]
Is this fixed in the current version of spotlight?
In the current version selecting and copying text seems to work in Firefox, Safari and Chrome.
