### ISSUE TITLE
Create filter based on "column" buttons in the issue view

### ISSUE THREAD

**Issue by ssuwelack** [Renumics/spotlight#192]
**Is your feature request related to a problem? Please describe.**
I typically use filter to understand issues better. Currently, I have to manually select them.

**Describe the solution you'd like**
There are already clickable "column" buttons in each issue. I would like to get a filter for the column (between min and max value).

**Describe alternatives you've considered**
Currently, I set the filter manually.

**Additional context**
![grafik](https://github.com/Renumics/spotlight/assets/6650719/d596cb38-95c3-4384-9df6-34d7f2c1ae02)

**Comment by neindochoh** [comment]
This should now be possible by dragging the column badge onto the filter bar.
