### ISSUE TITLE
Datasets containing text seem to slow down Spotlight significantly

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#207]
**Describe the bug**
When running spotlight on datasets containing longer text it feels like this significantly slows down the UI. Concretely, hovering on data points and waiting for the hover data to highlight seems very laggy.

**To Reproduce**
Run the following notebook in the sliceguard library: https://github.com/Renumics/sliceguard/blob/main/examples/quickstart_mixed_data.ipynb

Calling the report function will open up Spotlight and this is where I realized it is much slower than with other datatypes.

**Expected behavior**
Spotlight being as fast as with images or other unstructured data types.

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser Chrome
-   Spotlight Version [e.g. 1.3.0]

**Comment by neindochoh** [comment]
I failed to reproduce this using the same dataset but **not** using sliceguard.

Does this happen with running spotlight alone?
If so, can you pinpoint a widget that slows down the UI?

**Comment by neindochoh** [comment]
Closing this for now.
