### ISSUE TITLE
UMAP bug due to Numpy/Numba conflicts

### ISSUE THREAD

**Issue by ssuwelack** [Renumics/spotlight#26]
**Describe the bug**
Spotlight does not start because of an internal error in the UMAP package

**To Reproduce**
1. Create new virtual env
2. Create new notebook and run mnist tiny example
3. UMAP does not load and error output in console

**Expected behavior**
Normal startup and completed Simmap

**Desktop (please complete the following information):**
 - Ubuntu
 - Spotlight 1.0.0rc10

**Screenshot**
![Screenshot from 2023-04-21 09-43-40](https://user-images.githubusercontent.com/6650719/233574865-3a194ffd-c46f-48ab-95bc-f784418b00de.png)

**Additional context**
Downgrading the Numpy version to e.g. 1.23.5 solves the issue. Maybe we should pin the version?

**Comment by markus-stoll** [comment]
Thank you for reporting this issue. We apologize for the inconvenience this may have caused. 
We have been able to reproduce the problem you encountered with pip version 20.0.2. The up-to-date version of pip at the time of writing this response is 21.2.4. Upgrading to this version should resolve the issue with the UMAP package.

Please follow these steps to upgrade pip and install renumics-spotlight:

- Make sure you have activated your virtual environment.

- Upgrade pip using the following command:
`pip install --upgrade pip`

- After the upgrade is complete, install renumics-spotlight using the following command:
`pip install renumics-spotlight`

Now, you should be able to run the MNIST tiny example without encountering the internal error in the UMAP package.


It's worth mentioning that an error should have been displayed during the installation process, indicating that the numy version was compatible with numba.
Please let us know if upgrading pip resolves the issue, or if you need further assistance. We appreciate your feedback and will continue to work on improving our package

**Comment by ssuwelack** [comment]
Thanks for the fast reply, upgrading PIP does resolve the issue!
