### ISSUE TITLE
Unsucessfull instalation because of building wheel for pycatch22 (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by mariaculman18** [Renumics/spotlight#267]
When installing Spotlight with 'pip install renumics-spotlight sliceguard[all] scikit-learn', I run into an error with building the wheel for pycatch22. The source of the error was 'Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/'. My two-step solution:

1. Download and install Microsoft C++ Build Tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/, then restart your PC.
2. Install Spotlight again in a new environment with 'python -m pip install pycatch22==0.4.2 renumics-spotlight sliceguard[all] scikit-learn'

I am unsure if this relates to my PC or that pycatch22 just got a new release. But in case someone is running into the same issue.

**Comment by druzsan** [comment]
Thank you for reporting this behavior and even the solution!

We're going to place `pycatch22` into package extras, so it has to be installed when using `renumics.spotlight.dataset.descriptors` only.
