### ISSUE TITLE
ROUGE score for metrics widget

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#276]
**Is your feature request related to a problem? Please describe.**
It would be nice to have more metrics available in the [metrics widget](https://github.com/Renumics/spotlight/blob/main/src/widgets/MetricsWidget/metrics.ts).

**Describe the solution you'd like**
An additional metric should be added to the metrics widget displaying the [ROUGE score](https://en.wikipedia.org/wiki/ROUGE_(metric)) between two columns.

**Additional context**
[arxiv-summarization](https://huggingface.co/datasets/ccdv/arxiv-summarization)

**Comment by akashpambhar** [comment]
Hi, I would be happy to give it a try. Please assign me

**Comment by akashpambhar** [comment]
Hi @steffenslavetinsky, I checked on ROUGE score and found that there are multiple variants of it. So should I implement ROUGE-1 score, using space for tokenizing strings? Or do you suggest any other approach?

**Comment by steffenslavetinsky** [comment]
I think, in order to support the ROUGE score, we should at least implement ROUGE-N (1 and 2) and ROUGE-L. However, I also believe that not all three metrics need to be implemented in one pull request, and it could make sense to implement, for example, ROUGE-1 and ROUGE-2 in a single pull request. What do you think?

**Comment by akashpambhar** [comment]
Seems appropriate. I'll try to implement and raise a PR for ROUGE-1 and ROUGE-2 combined.
Thanks for the suggestion!

**Comment by markus-stoll** [comment]
@smrithi3 Are you still working on this?

**Comment by akashpambhar** [comment]
Hi @markus-stoll, I tried to setup project locally for development and I succeeded in installing all necessary dependencies. But when I try to run development server using `make dev,` it throws following error:
```
SPOTLIGHT_TABLE_FILE="data/tables/tallymarks-small.h5" SPOTLIGHT_DEV=${SPOTLIGHT_DEV:-true} poetry run spotlight --analyze-all
'SPOTLIGHT_TABLE_FILE' is not recognized as an internal or external command,
operable program or batch file.
make: *** [dev] Error 1
```  

Can you tell what's the problem with this, I'm unable to find a solution for this? Btw, I'm using Windows 10 OS
