### ISSUE TITLE
BLEU score Lens to compare two rows in a column

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#278]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a Lens showing the per column BLEU score in the Inspector widget [create a new Lens](https://renumics.com/docs/development/lenses).

**Describe the solution you'd like**
An additional Lens should be added to the Inspector widget displaying the [BLEU score](https://en.wikipedia.org/wiki/BLEU) between two columns.

**Additional context**
[arxiv-summarization](https://huggingface.co/datasets/ccdv/arxiv-summarization)

**Comment by MENNA123MAHMOUD** [comment]
Hi  @steffenslavetinsky I want to start working on this issue :pray:

**Comment by vishnukaushik** [comment]
@steffenslavetinsky @markus-stoll can I work on this?

**Comment by MENNA123MAHMOUD** [comment]
Hi @vishnukaushik, I already started working on this and am almost done with it.I  just need to test it more and do some cleaning up.
