### ISSUE TITLE
ROUGE score Lens to compare two rows in a column

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#279]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a Lens showing the per column ROUGE score in the Inspector widget [create a new Lens](https://renumics.com/docs/development/lenses).

**Describe the solution you'd like**
An additional Lens should be added to the Inspector widget displaying the [ROUGE score](https://en.wikipedia.org/wiki/ROUGE_(metric)) between two columns.

**Additional context**
[arxiv-summarization](https://huggingface.co/datasets/ccdv/arxiv-summarization)

**Comment by steffenslavetinsky** [comment]
This should be pretty similar to #276

**Comment by vishnukaushik** [comment]
@steffenslavetinsky could you assign this to me?
