### ISSUE TITLE
Misplaced Settings Icon in SequenceView Lens

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#281]
**Describe the bug**
The Settings Icon seems to be misplaced in the Sequence view

**To Reproduce**

1. Open a sequence in the SequenceVie Lens

**Screenshots**
![grafik](https://github.com/Renumics/spotlight/assets/30174043/7c83c273-d44c-459b-b8dc-a50c40b7d713)

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser safari, chrome, firefox
-   Browser Version latest as of 2023.10.19
-   Spotlight Version 1.5.3

**Additional context**
Provide any additional context or information that could be relevant to understanding the issue.

**Comment by sathudeva7** [comment]
@steffenslavetinsky I'd love to work on this issue

**Comment by steffenslavetinsky** [comment]
Unfortunately there already is a merge request for that.
But if you would like to work on another one, I'll get back to you later today.

**Comment by sathudeva7** [comment]
ok thanks for the reply

**Comment by steffenslavetinsky** [comment]
Closed by #282
