### ISSUE TITLE
Miscalculation in F1 metric

### ISSUE THREAD

**Issue by akashpambhar** [Renumics/spotlight#289]
**Describe the bug**
The F1 metric may be calculated incorrectly. 

**Expected behavior**
It should be as described in below reference links

**Screenshots**
Current code for F1 metric
![image](https://github.com/Renumics/spotlight/assets/71589813/24f21eee-bfc9-4b2e-bd26-81b89ea283d0)

**Additional context**

Observation from 
- https://en.wikipedia.org/wiki/F-score
- https://www.v7labs.com/blog/f1-score-guide

**Comment by akashpambhar** [comment]
Please assign me, if this is a relevant bug

**Comment by steffenslavetinsky** [comment]
I assigned you Akash.
Thx for submitting the issue 🚀.

**Comment by akashpambhar** [comment]
Thank you. Will submit a PR in sometime
