### ISSUE TITLE
Html widget to display e.g. plotly figures

### ISSUE THREAD

**Issue by markus-stoll** [Renumics/spotlight#29]
Is your feature request related to a problem? Please describe.
Yes, the problem is that currently there is no built-in capability to display plots that are highly customized for specific use cases. This makes it difficult to review of content that can not be rendered by the built-in 3d renderings and 2d graph plots.

Describe the solution you'd like
I would like the ability to render div HTML code within a widget, so that content generated by Plotly and other libraries can be easily displayed. This would involve adding a new widget type that can handle HTML code as input.

Describe alternatives you've considered
One alternative is to convert the HTML code to an image or a static plot, and then display that within the widget. However, this approach would not allow for interactive features such as zooming and panning, which are often present in Plotly figures. 

Additional context
Here is an example of how the new widget could be used:

```
import plotly.graph_objs as go
df["figs"]= [go.Figure(data=[go.Scatter(x=df.iloc[i]["x"], df.iloc[i]["y"] ).to_html()])
spotlight.show(df, dtype={""]=": spotlight.HTML_DIV})
```

**Comment by dani2112** [comment]
This could also be a step to enable NLP use cases. E.g. in voice analytics there is a large focus on working with the transcript of the audio file (emotion analytics etc.). Till now Spotlight does not support a multiline text view in the inspector. Probably a HTML view can be used to display multiline/formated text. It would be great if the text can be "arbitrary" long and can be copied from the view. Also highlighting of named entities would be a plus (not high priority but if it just works that's great).

I plan on also building an additional demo on the performance of the whisper model where the transcript plays a role. This could be used when testing the functionality of the view.
