### ISSUE TITLE
Youtube Tutorials for Renumics-spotlight

### ISSUE THREAD

**Issue by OjasMittal** [Renumics/spotlight#294]
Hi, I was looking through youtube if I could find some video tutorials which could guide me how to use various features of renumerics, but I couldn't find any. 
So a suggestion from my side,  If some youtube videos can be created which portray use of various features of renumics spotlight and some demo projects that would be really very helpful for developers to get started with it, and see its scope of implementing it in their businesses .

**Comment by dani2112** [comment]
Hey @OjasMittal! Great Suggestion! Do you have any use cases in mind that would be particularly interesting for you?

For now we already regularly post content, e.g. on Medium, that you could have a look at. Good places to look keep yourself updated are:
1. [Our Medium Reading List](https://medium.com/@markus.stoll/list/spotlight-d1a64f6d0ca4)
2. [Our Company Page on LinkedIn](https://www.linkedin.com/company/renumics/?)

**Comment by OjasMittal** [comment]
Hey @dani2112 , The content which is there on Medium is great, same content if can be posted as a video tutorial on Youtube , it would be just fantastic , as many developers find it convenient to learn and work on a new tech-stack if its step by step video-demonstration is available.
Just a suggestion from my side so that more and more people can get to know and use this amazing stuff :)

**Comment by steffenslavetinsky** [comment]
Great suggestion, I also prefer to watch a tutorial video instead of reading a long tutorial.

I added the hacktoberfest label to this issue.
To contribute, get in touch on our [discord](https://discord.gg/VAQdFCU5YD) if you woult like to discuss ideas and add a created video to the (to be created) **Ressources** in the README.md
