### ISSUE TITLE
Add the missing glossary terms

### ISSUE THREAD

**Issue by Smartmind12** [Renumics/spotlight#302]
Currently many of the glossary terms are missing and not formatted in the correct manner

I would like to propose and make a PR to add the description of the glosarry terms and indent the same as per righthand bar heirarchy.

![Screenshot 2023-10-24 at 11 55 57 AM](https://github.com/Renumics/spotlight/assets/91927689/ccd24595-fbf4-466d-8561-b3144e1d69ee)

Kindly let me know where the glossary page is located so that i can start working on the same.

**Comment by steffenslavetinsky** [comment]
We're giving our docs a makeover, so i think we should hold off on these tasks until the new ones are up and running.
