### ISSUE TITLE
Change website title on leaving it

### ISSUE THREAD

**Issue by kaal-coder** [Renumics/spotlight#307]
Motivation for this feature:-
The average time a person spends on a web page is 54 seconds. That’s not a lot of time, but we may be able to entice them to stay with an exit intent popup. 

How this feature will be useful:- 

- Keep visitors on your site for longer periods
- Increase conversions
- Decrease cart abandonment rates
- Grow email subscriber list

What changes will I make- 
When someone changes their tab while using the website, the website name will change and some message will appear. For example, "Come back soon 🥺" .

**Comment by dani2112** [comment]
Hey @kaal-coder! Thanks for your proposal. However, to me, it is not very clear how this applies to our application. Spotlight is an app that is used for a specific purpose and is designed to solve a problem, such as model evaluation, as fast as possible. So keeping a user on our web-based, locally running visualization software for longer is not really something that will give us a benefit. It is not a community website that profits from keeping users on the platform as long as possible.

Could you clarify what you intend to do or if this is a misunderstanding close the issue?

Best,

Daniel

**Comment by kaal-coder** [comment]
Thinking about the long run, this feature might be helpful.
If not, then please close the issue @dani2112 or else assign me :)
Thanks !
