### ISSUE TITLE
DataGrid does not prevent builtin context menu from becoming visible

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#32]
**Describe the bug**
On right click in the DataGrid (onContextMenu) the Browsers Builtin context menu overlays spotlights context menu

**To Reproduce**
1. Open a dataset in a DataGrid
2. right click on any cell

**Expected behavior**
I would expect the browser menu to not show, when there is another menu provided by spotlight

**Screenshots**

https://user-images.githubusercontent.com/30174043/237054951-4df14427-3173-4f62-887e-e678e725d5b6.mov

Desktop (please complete the following information):

OS: macOS 12.3.1
Browser: chrome
Version: 112.0.5615.137 (Official Build) (arm64)

**Comment by steffenslavetinsky** [comment]
preventing default behavior and stopping propagation could solve it in

/frontend/src/components/widgets/DataGrid/GridContextMenu.tsx
``` typescript
const onContextMenu = useCallback((event: MouseEvent<HTMLElement>) => {
        const el = (event.target as HTMLElement).closest(
            'div[data-rowindex]'
        ) as HTMLElement;

        setColumnIndex(+(el?.dataset?.columnindex || -1));
        setRowIndex(+(el?.dataset?.rowindex || -1));

        event.preventDefault();
        event.stopPropagation();
    }, []);
```

**Comment by neindochoh** [comment]
This should be fixed now.
