### ISSUE TITLE
Run Spotlight in Jupyter Notebook Environments without Port Forwarding

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#325]
**Is your feature request related to a problem? Please describe.**
A common scenario is that data analysis is performed in notebook environments that are run on cloud services, K8S, or something comparable.
Spotlight can be started from a notebook but cannot run in the notebook environment itself, which makes forwarding the port Spotlight is operating on mandatory.
It would be interesting to explore what is necessary to make Spotlight integrate with notebook environments seamlessly.
Also, is there any workarounds one could use in this scenario?

**Describe the solution you'd like**
Spotlight operates normally but doesn't require port forwarding.

** Additional Context **
Question asked by "Marco" on Discord.

**Comment by markus-stoll** [comment]
How about ngrok (https://ngrok.com/ - its free but you need an account)? as workaround. 
The setup can be done from within the notebook without touching the kubernetes config. But  It would route the traffic via their servers.

**Comment by dani2112** [comment]
@markus-stoll Yes, if the data is not sensitive and can be sent over ngrok's servers, that could be a solution. Do you have any ideas on how we could also provide a solution for enterprise environments? I guess the K8S environment in the original question is a hint more toward that direction.

**Comment by mcrisafu** [comment]
Hi I am "Marco" from Discord. Thank you @dani2112  to open this issue. @markus-stoll , thank you for the workaround. This would indeed work. But as @dani2112 guessed correctly, we can not do that due to the nature of the data.
