### ISSUE TITLE
Spotlight layout cannot be loaded with API

### ISSUE THREAD

**Issue by ssuwelack** [Renumics/spotlight#34]
**Describe the bug**
It seems as if the "layout" argument is ignored when loading Spotlight. It doesn't load up with the right layout, but I can select "load layout" in the GUI just fine.

**To Reproduce**
1. Download dataset:
dataset = datasets.load_dataset("renumics/cifar100-enriched", split="all")
df = dataset.to_pandas()
df.drop(columns=['embedding', 'probabilities'], inplace=True)
2. Load spotlight:
spotlight.show(df, dtype={'embedding_reduced': spotlight.Embedding, 'image':spotlight.Image})
4. Save two different layouts
5. Load the layouts: 
spotlight.show(df, dtype={'embedding_reduced': spotlight.Embedding, 'image':spotlight.Image}, layout="mylayout.json")
6. The layout is not loaded, but can be loaded in the GUI

**Expected behavior**
Layout should be set to saved layout

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Firefox
 - Spotlight Version rc10

**Additional context**

**Comment by Renumics** [comment]
done
