### ISSUE TITLE
Dtype of sequence in Huggingface dataset is not automatically detected

### ISSUE THREAD

**Issue by ssuwelack** [Renumics/spotlight#357]
**Describe the bug**
I created a dataset that contains time series data with dimensions (N,2) and converted it to a Hugging Face dataset. The Python list of lists is then automatically converted to the Sequence data type. This is not recognized as Sequence1D when loading the dataset.

**To Reproduce**

1. Load dataset from Hugging Face: ds=dataset.load_dataset('renumics/f1_dataset, split='train)
2. spotlight.show(ds)
3. Observe the error

**Additional context**
Demo space: https://huggingface.co/spaces/renumics/spotlight-racing-data

**Comment by neindochoh** [comment]
Unfortunately, we cannot distinguish if an array of shape [N,2] represents a Timeseries (`Sequence1D`)  or a List of 1d regions (`Sequence<window>`) without a user-supplied specification of the actual `dtype`.

Currently, we choose  `Sequence<window>` by default for shape [N,2] and `Sequence1D` for shape [2,N].

We are happy about ideas to improve this behavior, but I am closing this issue for now.

**Comment by neindochoh** [comment]
We are happy about ideas to improve this behavior, but I am closing this issue for now.

**Comment by druzsan** [comment]
I could reproduce this bug so I reopen this issue. The actual shape of sequences in the dataset is `[2, n]` though.
