### ISSUE TITLE
🏀 Playbook link doesn't work.

### ISSUE THREAD

**Issue by m-pektas** [Renumics/spotlight#394]
**Describe the bug**
🏀 [Playbook](https://renumics.com/docs/playbook/) link in the readme file doesn't work.

**To Reproduce**

1. Open readme.
2. Move to the "Learn more about unstructured data workflows" section.
3. Click to 🏀 [Playbook](https://renumics.com/docs/playbook/) link.
4. Observe the "This page does not exist" page.

**Screenshots**
<img width="622" alt="Screenshot 2024-01-16 at 11 26 32" src="https://github.com/Renumics/spotlight/assets/15729405/e105aed4-370d-43c8-b7f4-f7cb47de8cec">

**Comment by ssuwelack** [comment]
Thanks for pointing that out!

I fixed the link will close the issue when it's merged.

Pull request #396

**Comment by ssuwelack** [comment]
merged
