### ISSUE TITLE
Spotlight Frontend crashes when accessing it on remote host without https -> crypto.randomUUID is not a function.

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#436]
**Describe the bug**
Spotlight crashes with crypto.randomUUID is not a function. This happens when Spotlight is accessed on a remote host without https. E.g., on a EC2 instance. The crypto API is not available when used without https outside of localhost.

**To Reproduce**

1. Spin up Spotlight and expose on 0.0.0.0
2. Access from other host via HTTP

You will see a blank page as the javascript crashes.

**Expected behavior**
It should not crash.

**Screenshots**
If possible, include screenshots or screen recordings to better illustrate the issue.

**Desktop (please complete the following information):**
Chrome 121

**Additional context**
Was an issue from Discord. Workaround was to forward port to localhost via VSCODE remote development but this is annoying.

**Comment by druzsan** [comment]
From now on, you can pass SSL key and certificate to Spotlight at start.
## Python
```python
spotlight.show(dataset, host="0.0.0.0", port=5000, ssl_keyfile="path/to/key", ssl_certfile="path/to/cert")
```
If the key file is locked, you will be prompted to enter the password. Alternatively, you cann pass it to `show`:
```python
spotlight.show(..., ssl_keyfile_password="password")
```
## CLI
```shell
spotlight --host 0.0.0.0 --port 5000 --ssl-keyfile path/to/key --ssl-certfile path/to/cert [--ssl-keyfile-password password] dataset
```
