### ISSUE TITLE
Bounding Boxes Not Displayed in Spotlight Visualization

### ISSUE THREAD

**Issue by dichrogfx** [Renumics/spotlight#443]
**Describe the bug**
I'm encountering a bug in Renumics Spotlight where bounding boxes are not being displayed in the visualization. There seems to be a lack of explicit documentation regarding the format of bounding boxes, which complicates troubleshooting.

**To Reproduce**

1.    Create a DataFrame with image paths and bounding box data.
2.   Invoke the show function in Spotlight to visualize the DataFrame.
3.    Bounding boxes fail to appear in the interface.

**Expected behavior**
Bounding boxes should be visible on the images.

**Screenshots**

![image](https://github.com/Renumics/spotlight/assets/35726298/827fb706-0f64-4aa1-ac67-b159f1d76bbb)
![image](https://github.com/Renumics/spotlight/assets/35726298/8bcf55d3-095b-400f-83df-6b78ec13c22c)

**Desktop**

    OS: Ubuntu
    Browser: Firefox
    Version: 122.0.1
    Spotlight Version: 1.6.7

**Additional context**
The DataFrame includes columns for 'filename', 'width', 'height', 'class', 'xmin', 'ymin', 'xmax', 'ymax', 'x_center', 'y_center', and 'bbox', with bounding box coordinates in the format [x_min, y_min, width, height].

**Comment by druzsan** [comment]
Hi @dichrogfx, we only enable simple data views by default, but you should be able to _configure_ the **BoundingBox** view.

⚠️ However, we expect bounding boxes as [x_min, y_min, x_max, y_max] between 0 and 1, so you have to adjust it.

To configure the **BoundingBox** view, click at the **Add View** icon in the top-right corner of the **Inspector** widget, then choose `filename`, `bboxs` and _optionally_ the labels column (should have the same amount of labels as `bboxs` does, probably `class` in your case). The **BoundingBox** view should be chosen by default, so just click at the `Add View` button.

Please tell us whether it worked for you.

P.S.: If you are not only showing the resulting `DataFrame`, but contantly changing it between shows, it can be inconvenient to manually set up the **Bounding Box** view in UI every time. In this case, you can preconfigure [Spotlight layout](https://renumics.com/api/spotlight/layout/) for your data via Python API.

**Comment by dichrogfx** [comment]
It works, thank you!
