### ISSUE TITLE
Can't access from WSL2

### ISSUE THREAD

**Issue by tylertitsworth** [Renumics/spotlight#444]
**Describe the bug**
I'm trying to use Spotlight from WSL2 + VSCode on the Windows 11 system. When I run my application to launch spotlight, my terminal becomes a blank canvas with the text `<<↑ ↓ Viewing <Spotlight>` in the bottom left-hand corner. I try to browse to `localhost:5000` in my browser there is nothing, checking the browser console shows a `404` error when trying to get `index.html`.

When I try to utilize my terminal or terminate the application, I find that I no longer have control of my terminal and I must close it using VSCode.

**To Reproduce**

1. Remote into WSL2, Ubuntu22.04
2. Install renumics-spotlight
3. Port-forward 5000 in VSCode
4. run with the following code snippet:
```python
...
from renumics import spotlight
spotlight.show(df, host="localhost", port=5000)
```
5. Run the python script and attempt to browse `localhost:5000`
6. Attempt to terminate the application with ctrl+c

**Expected behavior**
The Spotlight UI should be accessible. My terminal should allow me to ctrl+c to terminate the application.

**Screenshots**
If possible, include screenshots or screen recordings to better illustrate the issue.

![image](https://github.com/Renumics/spotlight/assets/43555799/558f63b6-4142-41ce-adb4-6042c2d1df67)
![image](https://github.com/Renumics/spotlight/assets/43555799/d3522136-3d2f-4593-97be-016ca393385d)

**Desktop (please complete the following information):**

-   OS: Win11
-   Browser Firefox
-   Browser Version 123.0
-   Spotlight Version 1.6.7

**Additional context**
I am trying to follow this article: https://itnext.io/visualize-your-rag-data-eda-for-retrieval-augmented-generation-0701ee98768f

**Comment by neindochoh** [comment]
Thanks a lot for your bug report! We are looking into it.

**Comment by neindochoh** [comment]
We tried to reproduce this under WSL2. (Sadly) it didn't fail on our Windows machine.

Did you remote into WSL from another or the same machine?
Could you try to run it again with a simple Dataframe and verbose output (set env var SPOTLIGHT_VERBOSE=true)?
```python
import pandas as pd
from renumics import spotlight
df = pd.DataFrame({"foo": range(4)})
spotlight.show(df)
```
As a workaround, you might be able to run everything directly under Windows instead of WSL.

**Comment by tylertitsworth** [comment]
I remoted into WSL from the same machine (Windows host).
I tried the code snippet you posted, and got the same results. I clicked somewhere in the empty space shown in my screenshot and it printed what looks like a utf-8 character to my terminal, after clicking around some more it seems like I'm able to interact with the UI elements even though I can't see them. I ended up getting a menu I can't close out of:
![image](https://github.com/Renumics/spotlight/assets/43555799/dff94e5f-cccd-461b-911a-9b4b60783e47)
When I browse to the address, I'm able to access the UI for the spotlight application!

Thing is, when I set the port, I can't replicate this experience, nor can I access the UI like I did when I didn't set the port value.

**Comment by tylertitsworth** [comment]
Hi, that flag did the trick. I didn't you know your program supports these flags and I found the docs didn't give me an easy path to find server configuration.

I also found that spotlight used a bit more memory than I have available in addition to the dataframe I'm trying to load into memory, so I have since stopped working with this package.

Thanks for your help.
