### ISSUE TITLE
TLS support required makes dockerized app difficult to deploy

### ISSUE THREAD

**Issue by dan-s-mueller** [Renumics/spotlight#447]
**Is your feature request related to a problem? Please describe.**
I am trying to use spotlight within a dockerized application. When I use the viewer.show application with host=0.0.0.0, I am required to use a TLS certificate. 

**Describe the solution you'd like**
Within the dockerized application, I would like the option to bypass this requirement in order to easily allow the spotlight viewer to open alongside another application I have on a different port within the container (e.g. a streamlit application).

**Describe alternatives you've considered**
Spotlight will work if you upload a certificate+key, but this requires including it in your docker container and makes publishing an application with this difficult because the key would have to be public.

**Additional context**
Functionality as of renumics-spotlight=1.6.6 supports this functionality.

**Comment by druzsan** [comment]
Hi @dan-s-mueller, we built in a flag for ignoring TLS certificate when starting Spotlight on non-localhost. Just use
```
spotlight --host 0.0.0.0 --no-ssl ...
```

**Comment by druzsan** [comment]
Hi @dan-s-mueller, the made changes are released in the Spotlight 1.6.9.
