### ISSUE TITLE
Choose more suitable scaling for spectrogram y-axis as a default

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#79]
**Is your feature request related to a problem? Please describe.**
The default axis scaling in the spectogram widget is set to logarithmic. This doesn't make much sense for a lot of real-world use cases, such as condition monitoring (exceptions are mostly related to music analysis -> converting frequency to pitches).

**Describe the solution you'd like**
Not having logarithmic scaling on the y axis by default. What could make sense but is no high priority for me personally is scaling the colorcoding of the signal energy logarithmically (converting to dB). Potentially it could also make sense to allow choosing the mel scale as the y-axis to match human hearing perception in the visual signal representation. Choosing y-axis range in a synchronized way (sync between samples) could also be a useful addition

**Describe alternatives you've considered**
-

**Additional context**
![Screenshot from 2023-06-02 12-03-14](https://github.com/Renumics/spotlight/assets/6371429/e1fcbd3d-8f65-47e9-a9e6-038ab2ebdac2)
Spectrogram default view when rendered with a speech signal. Will almost always look like this.

**Comment by tarekt** [comment]
Changed default scale to linear in #169.
