### ISSUE TITLE
Drag'n'Drop views in InspectorView not working

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#84]
**Describe the bug**
I can't drag'n'drop the views in the inspector in order to change their ordering.

**To Reproduce**

1. Add multiple views to the inspector
2. Try changing the order with drag'n'drop

**Expected behavior**
I would expect to be able to change the order of the views

**Desktop (please complete the following information):**

-   OS: macos
-   Browser: chrome
-   Browser Version: 114.0.5735.90 (Official Build) (arm64)
-   Spotlight Version 1.0.0

**Additional context**

react-beautiful-dnd prints the following debug error message:
```
Unable to find draggable with id: 0e6631f7-1128-4558-9966-8e9175969c9
```

when i inspect the Elements, I can find the draggable with the searched id:

```html
<div data-rbd-draggable-context-id="1" data-rbd-draggable-id="0e6631f7-1128-4558-9966-8e9175969c91" tabindex="0" role="button" aria-describedby="rbd-hidden-text-1-hidden-text-1" data-rbd-drag-handle-draggable-id="0e6631f7-1128-4558-9966-8e9175969c91" data-rbd-drag-handle-context-id="1" draggable="false" class="Row__RowItemWrapper-sc-v9a0x9-0 fCdhiJ" style="position: absolute; left: 0px; top: 44px; height: 64px; width: 100%;">
  <button class="Button__StyledHTMLButton-sc-1xm6gdl-0 jqfzFA">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="X__StyledSvg-sc-1dqpkgl-0 PyruS">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12">
      </path>
    </svg>
  </button>
  <div class="Row__ViewNameWrapper-sc-v9a0x9-1 dfmceQ">
    <div>
      <span class="Row__ViewName-sc-v9a0x9-2 ebvlsi">
        less_categories
      </span>
    </div>
  </div>
</div>
```

**Comment by Renumics** [comment]
Drag and drop is not supported at the moment and the feature was removed for now.
