### ISSUE TITLE
Persist Filters

### ISSUE THREAD

**Issue by steffenslavetinsky** [Renumics/spotlight#88]
**Is your feature request related to a problem? Please describe.**
At the moment filters are not persisted on a reload

**Describe the solution you'd like**
I would like the filters I arranged to be persisted and still exist after reload.

**Describe alternatives you've considered**
I don't think there is a feasible alternative and user feedback suggests, that filters are not used as extensive as they could be because there is a chance of loosing your work on a reload.

**Additional context**

**Comment by Renumics** [comment]
In a first version only not-index-based filter will be stored.
